# -*- coding: utf-8 -*-
"""UAS-PCD-FIX

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rT_fLdn82yl_fkV2lU0bqExwGw-FJ1Mi

## 1. Import library
"""

import cv2
import numpy as np
from pathlib import Path
from IPython.display import Video, display
import matplotlib.pyplot as plt

"""## 2. Parameter utama"""

VIDEO_PATH = 'dataset/Sample_Video_HighQuality.mp4'
OUTPUT_PATH = 'hasil_deteksi_v3.mp4'
METHOD = 'running_avg'

RESIZE_WIDTH = 960
RUNNING_AVG_ALPHA     = 0.05
RUNNING_AVG_THRESHOLD = 30
WARMUP_FRAMES = 60
MIN_AREA_TOP    = 120
MIN_AREA_MIDDLE = 350
MIN_AREA_BOTTOM = 600
MAX_BOX_AREA_RATIO = 0.030
DILATE_ITER = 1
REVIEW_INTERVAL = 30

video_file = Path(VIDEO_PATH)
print('Video ditemukan:', video_file.exists())
print('Path:', video_file.resolve() if video_file.exists() else video_file)
print(f'Metode          : {METHOD}')
print(f'Alpha           : {RUNNING_AVG_ALPHA}  (background adaptif)')
print(f'Warmup frames   : {WARMUP_FRAMES}')
print(f'Review interval : setiap {REVIEW_INTERVAL} frame')

"""## 3. ROI area jalan

Kalau ada kendaraan pinggir yang tidak terdeteksi, perluas polygon ROI sedikit.
"""

def make_road_roi_mask(frame):
    height, width = frame.shape[:2]
    mask = np.zeros((height, width), dtype=np.uint8)

    road_polygon = np.array([
        (0, int(height * 0.40)),
        (int(width * 0.42), int(height * 0.23)),
        (int(width * 0.64), int(height * 0.23)),
        (width, int(height * 0.33)),
        (width, height),
        (0, height),
    ], dtype=np.int32)

    cv2.fillPoly(mask, [road_polygon], 255)
    return mask


def apply_roi(mask, roi_mask):
    return cv2.bitwise_and(mask, roi_mask)

"""## 4. Fungsi deteksi konservatif"""

def preprocess_frame(frame, width=960):
    h, w = frame.shape[:2]
    scale = width / w
    resized = cv2.resize(frame, (width, int(h * scale)))
    gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (5, 5), 0)
    return resized, gray


def clean_mask_conservative(mask):
    # Open: hapus noise titik kecil
    kernel_open = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    # Close: tutup celah kecil dalam blob kendaraan
    kernel_close = cv2.getStructuringElement(cv2.MORPH_RECT, (7, 7))
    # Dilate: perlebar sedikit, DILATE_ITER=1 agar blob tidak bergabung
    kernel_dilate = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 3))

    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  kernel_open,  iterations=2)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel_close, iterations=1)
    if DILATE_ITER > 0:
        mask = cv2.dilate(mask, kernel_dilate, iterations=DILATE_ITER)
    return mask


def create_mog2_mask(background_subtractor, current_frame):
    mask = background_subtractor.apply(current_frame)
    _, mask = cv2.threshold(mask, 220, 255, cv2.THRESH_BINARY)
    return clean_mask_conservative(mask)


def create_running_avg_mask(avg_background, current_gray):
    cv2.accumulateWeighted(current_gray, avg_background, RUNNING_AVG_ALPHA)
    background_model = cv2.convertScaleAbs(avg_background)
    frame_delta = cv2.absdiff(current_gray, background_model)
    _, mask = cv2.threshold(frame_delta, RUNNING_AVG_THRESHOLD, 255, cv2.THRESH_BINARY)
    return clean_mask_conservative(mask), avg_background


def min_area_by_perspective(center_y, frame_height):
    y_ratio = center_y / frame_height
    if y_ratio < 0.42:
        return MIN_AREA_TOP
    if y_ratio < 0.68:
        return MIN_AREA_MIDDLE
    return MIN_AREA_BOTTOM


def max_box_size_by_perspective(center_y, frame_width, frame_height):
    y_ratio = center_y / frame_height
    if y_ratio < 0.42:
        max_w = frame_width  * 0.09
        max_h = frame_height * 0.10
    elif y_ratio < 0.68:
        max_w = frame_width  * 0.18
        max_h = frame_height * 0.20
    else:
        max_w = frame_width  * 0.30
        max_h = frame_height * 0.36
    return max_w, max_h


def box_inside_reasonable_perspective(x, y, w, h, frame_width, frame_height):
    center_y = y + h / 2
    max_w, max_h = max_box_size_by_perspective(center_y, frame_width, frame_height)
    if w > max_w or h > max_h:
        return False
    if w * h > frame_width * frame_height * MAX_BOX_AREA_RATIO:
        return False
    return True


def find_vehicle_candidates(mask):
    frame_height, frame_width = mask.shape[:2]
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    boxes = []

    for contour in contours:
        area = cv2.contourArea(contour)
        x, y, w, h = cv2.boundingRect(contour)
        if w < 10 or h < 10:
            continue

        center_y = y + h / 2
        min_area = min_area_by_perspective(center_y, frame_height)
        if area < min_area:
            continue
        aspect_ratio = w / h
        if aspect_ratio < 0.50 or aspect_ratio > 4.0:
            continue
        bbox_area = w * h
        rectangularity = area / bbox_area if bbox_area > 0 else 0
        if rectangularity < 0.25:
            continue

        if not box_inside_reasonable_perspective(x, y, w, h, frame_width, frame_height):
            continue

        boxes.append([x, y, x + w, y + h, float(area)])

    return boxes


def iou(box_a, box_b):
    ax1, ay1, ax2, ay2, _ = box_a
    bx1, by1, bx2, by2, _ = box_b
    ix1 = max(ax1, bx1); iy1 = max(ay1, by1)
    ix2 = min(ax2, bx2); iy2 = min(ay2, by2)
    iw = max(0, ix2 - ix1); ih = max(0, iy2 - iy1)
    inter = iw * ih
    area_a = max(0, ax2 - ax1) * max(0, ay2 - ay1)
    area_b = max(0, bx2 - bx1) * max(0, by2 - by1)
    union  = area_a + area_b - inter
    return inter / union if union > 0 else 0


def nms(boxes, threshold=0.20):
    selected = []
    boxes = sorted(boxes, key=lambda b: b[4], reverse=True)
    while boxes:
        current = boxes.pop(0)
        selected.append(current)
        boxes = [b for b in boxes if iou(current, b) < threshold]
    return selected


def remove_boxes_inside_larger_boxes(boxes):
    kept = []
    for i, box in enumerate(boxes):
        x1, y1, x2, y2, _ = box
        area = (x2 - x1) * (y2 - y1)
        inside = False
        for j, other in enumerate(boxes):
            if i == j:
                continue
            ox1, oy1, ox2, oy2, _ = other
            other_area = (ox2 - ox1) * (oy2 - oy1)
            if other_area <= area:
                continue
            if x1 >= ox1 and y1 >= oy1 and x2 <= ox2 and y2 <= oy2:
                inside = True
                break
        if not inside:
            kept.append(box)
    return kept


def postprocess_boxes(boxes):
    boxes = nms(boxes, threshold=0.20)
    boxes = remove_boxes_inside_larger_boxes(boxes)
    return boxes

"""## 5. Visualisasi"""

def draw_detections(frame, boxes):
    for index, (x1, y1, x2, y2, score) in enumerate(boxes, start=1):
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            frame,
            f'Kendaraan {index}',
            (x1, max(y1 - 8, 18)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.50,
            (0, 255, 0),
            2,
        )

    cv2.putText(
        frame,
        f'Detected: {len(boxes)}',
        (20, 35),
        cv2.FONT_HERSHEY_SIMPLEX,
        1,
        (0, 255, 255),
        2,
    )
    return frame


def show_bgr(image, title='Image'):
    plt.figure(figsize=(14, 6))
    plt.title(title)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()


def show_gray(image, title='Mask'):
    plt.figure(figsize=(14, 6))
    plt.title(title)
    plt.imshow(image, cmap='gray')
    plt.axis('off')
    plt.show()

"""## 6. Preview ROI"""

cap = cv2.VideoCapture(VIDEO_PATH)
ret, frame = cap.read()
cap.release()

if not ret:
    raise RuntimeError('Video tidak bisa dibaca. Periksa VIDEO_PATH.')

frame_resized, _ = preprocess_frame(frame, width=RESIZE_WIDTH)
roi_mask = make_road_roi_mask(frame_resized)
roi_preview = frame_resized.copy()
roi_preview[roi_mask == 0] = (roi_preview[roi_mask == 0] * 0.25).astype(np.uint8)
show_bgr(roi_preview, 'ROI Area Jalan')

"""## 7. Preview satu frame

Ubah `frame_index` untuk mengecek frame lain.
"""

def detect_single_preview(frame_index=120):
    cap = cv2.VideoCapture(VIDEO_PATH)
    if not cap.isOpened():
        raise RuntimeError('Video tidak bisa dibuka. Cek VIDEO_PATH.')

    background_subtractor = cv2.createBackgroundSubtractorMOG2(
        history=300, varThreshold=32, detectShadows=True
    )

    ret, first_frame = cap.read()
    if not ret:
        cap.release()
        raise RuntimeError('Video tidak memiliki frame.')

    _, first_gray = preprocess_frame(first_frame, width=RESIZE_WIDTH)
    avg_background = np.float32(first_gray)
    current_index  = 1

    for _ in range(WARMUP_FRAMES - 1):
        ret, frame = cap.read()
        if not ret:
            cap.release()
            raise RuntimeError('Video lebih pendek dari WARMUP_FRAMES.')
        _, wgray = preprocess_frame(frame, width=RESIZE_WIDTH)
        cv2.accumulateWeighted(wgray, avg_background, RUNNING_AVG_ALPHA)
        current_index += 1

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        current_frame, current_gray = preprocess_frame(frame, width=RESIZE_WIDTH)
        roi_mask = make_road_roi_mask(current_frame)

        if METHOD == 'running_avg':
            mask, avg_background = create_running_avg_mask(avg_background, current_gray)
        elif METHOD == 'mog2':
            mask = create_mog2_mask(background_subtractor, current_frame)
        else:
            cap.release()
            raise ValueError(f'METHOD tidak dikenal: {METHOD}. Pilih running_avg atau mog2.')

        mask  = apply_roi(mask, roi_mask)
        boxes = find_vehicle_candidates(mask)
        boxes = postprocess_boxes(boxes)

        if current_index >= frame_index:
            result = draw_detections(current_frame.copy(), boxes)
            cap.release()
            show_gray(mask, 'Motion Mask')
            show_bgr(result, f'Preview Frame {frame_index}')
            print('Jumlah kendaraan terdeteksi:', len(boxes))
            return boxes

        current_index += 1

    cap.release()
    raise RuntimeError(
        f'Frame {frame_index} tidak ditemukan. '
        f'Video hanya memiliki {current_index} frame setelah warmup.'
    )

preview_boxes = detect_single_preview(frame_index=120)

"""## 8. Proses seluruh video"""

def process_video():
    cap = cv2.VideoCapture(VIDEO_PATH)
    if not cap.isOpened():
        raise RuntimeError(f'Gagal membuka video: {VIDEO_PATH}')

    fps = cap.get(cv2.CAP_PROP_FPS) or 25

    ret, first_frame = cap.read()
    if not ret:
        cap.release()
        raise RuntimeError('Video tidak memiliki frame.')

    first_resized, first_gray = preprocess_frame(first_frame, width=RESIZE_WIDTH)
    height, width = first_resized.shape[:2]

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    writer = cv2.VideoWriter(OUTPUT_PATH, fourcc, fps, (width, height))

    background_subtractor = cv2.createBackgroundSubtractorMOG2(
        history=300, varThreshold=32, detectShadows=True
    )
    avg_background = np.float32(first_gray)

    frame_number     = 1
    total_detections = 0
    interval_counts  = []
    review_log       = []
    interval_start   = 1

    print(f'Warmup {WARMUP_FRAMES} frame...')
    for _ in range(WARMUP_FRAMES - 1):
        ret, frame = cap.read()
        if not ret:
            break
        _, wgray = preprocess_frame(frame, width=RESIZE_WIDTH)
        cv2.accumulateWeighted(wgray, avg_background, RUNNING_AVG_ALPHA)
        frame_number += 1
    print('Warmup selesai. Mulai deteksi...')

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        current_frame, current_gray = preprocess_frame(frame, width=RESIZE_WIDTH)
        roi_mask = make_road_roi_mask(current_frame)

        if METHOD == 'running_avg':
            mask, avg_background = create_running_avg_mask(avg_background, current_gray)
        elif METHOD == 'mog2':
            mask = create_mog2_mask(background_subtractor, current_frame)
        else:
            raise ValueError(f'METHOD tidak dikenal: {METHOD}')

        mask  = apply_roi(mask, roi_mask)
        boxes = find_vehicle_candidates(mask)
        boxes = postprocess_boxes(boxes)

        count_this_frame = len(boxes)
        total_detections += count_this_frame
        interval_counts.append(count_this_frame)

        result = draw_detections(current_frame.copy(), boxes)
        writer.write(result)

        if frame_number % REVIEW_INTERVAL == 0:
            avg_iv = sum(interval_counts) / len(interval_counts)
            entry  = (
                f'Frame {interval_start:>5} - {frame_number:>5} | '
                f'Avg: {avg_iv:5.2f} | '
                f'Max: {max(interval_counts):>3} | '
                f'Min: {min(interval_counts):>3} | '
                f'Total: {sum(interval_counts):>5}'
            )
            review_log.append(entry)
            print(entry)
            interval_counts = []
            interval_start  = frame_number + 1

        frame_number += 1

    cap.release()
    writer.release()

    if interval_counts:
        avg_iv = sum(interval_counts) / len(interval_counts)
        entry  = (
            f'Frame {interval_start:>5} - {frame_number - 1:>5} | '
            f'Avg: {avg_iv:5.2f} | '
            f'Max: {max(interval_counts):>3} | '
            f'Min: {min(interval_counts):>3} | '
            f'Total: {sum(interval_counts):>5}  (sisa frame)'
        )
        review_log.append(entry)
        print(entry)

    print()
    print('SELESAI')
    print(f'Output          : {OUTPUT_PATH}')
    print(f'Metode          : {METHOD}')
    print(f'Jumlah frame    : {frame_number - 1}')
    print(f'Total deteksi   : {total_detections}')
    print(f'Rata-rata/frame : {total_detections / max(1, frame_number - 1):.2f}')
    print('=' * 60)
    return review_log

review_log = process_video()

"""## 8b. Review & Analisis Jumlah Kendaraan per Interval

Cell ini membaca ulang video, menghitung jumlah kendaraan yang terdeteksi setiap `REVIEW_INTERVAL` frame setelah warmup, lalu menampilkan tabel dan grafik ringkasan.

"""

def review_detections_per_interval(
    video_path=VIDEO_PATH,
    interval=REVIEW_INTERVAL,
    warmup_frames=WARMUP_FRAMES,
    save_path='review_deteksi_interval.png'
):
    if interval <= 0:
        raise ValueError('interval harus lebih besar dari 0.')

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f'Gagal membuka video: {video_path}')

    fps = cap.get(cv2.CAP_PROP_FPS) or 25

    ret, first_frame = cap.read()
    if not ret:
        cap.release()
        raise RuntimeError('Video tidak memiliki frame.')

    first_resized, first_gray = preprocess_frame(first_frame, width=RESIZE_WIDTH)
    avg_background = np.float32(first_gray)

    background_subtractor = cv2.createBackgroundSubtractorMOG2(
        history=300,
        varThreshold=32,
        detectShadows=True
    )

    last_read_frame_number = 1

    while last_read_frame_number < warmup_frames:
        ret, frame = cap.read()
        if not ret:
            break

        warm_frame, warm_gray = preprocess_frame(frame, width=RESIZE_WIDTH)

        if METHOD == 'running_avg':
            cv2.accumulateWeighted(warm_gray, avg_background, RUNNING_AVG_ALPHA)
        elif METHOD == 'mog2':
            background_subtractor.apply(warm_frame)
        else:
            cap.release()
            raise ValueError(f'METHOD tidak dikenal: {METHOD}')

        last_read_frame_number += 1

    summary = []
    counts_buffer = []
    interval_start = last_read_frame_number + 1

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        current_frame_number = last_read_frame_number + 1
        current_frame, current_gray = preprocess_frame(frame, width=RESIZE_WIDTH)
        roi_mask = make_road_roi_mask(current_frame)

        if METHOD == 'running_avg':
            mask, avg_background = create_running_avg_mask(avg_background, current_gray)
        elif METHOD == 'mog2':
            mask = create_mog2_mask(background_subtractor, current_frame)
        else:
            cap.release()
            raise ValueError(f'METHOD tidak dikenal: {METHOD}')

        mask = apply_roi(mask, roi_mask)
        boxes = postprocess_boxes(find_vehicle_candidates(mask))
        counts_buffer.append(len(boxes))

        if len(counts_buffer) == interval:
            total = sum(counts_buffer)
            summary.append({
                'start_frame': interval_start,
                'end_frame': current_frame_number,
                'total_deteksi': total,
                'rata_rata': total / len(counts_buffer),
                'maks': max(counts_buffer),
                'min': min(counts_buffer),
                'mulai_detik': interval_start / fps,
                'akhir_detik': current_frame_number / fps,
            })
            counts_buffer = []
            interval_start = current_frame_number + 1

        last_read_frame_number = current_frame_number

    cap.release()

    if counts_buffer:
        total = sum(counts_buffer)
        summary.append({
            'start_frame': interval_start,
            'end_frame': last_read_frame_number,
            'total_deteksi': total,
            'rata_rata': total / len(counts_buffer),
            'maks': max(counts_buffer),
            'min': min(counts_buffer),
            'mulai_detik': interval_start / fps,
            'akhir_detik': last_read_frame_number / fps,
        })

    if not summary:
        print('Tidak ada frame yang diproses setelah warmup. Coba kecilkan WARMUP_FRAMES.')
        return []

    print('Review jumlah kendaraan per interval')
    print('Metode          : {}'.format(METHOD))
    print('Interval        : {} frame'.format(interval))
    print('Warmup          : {} frame'.format(min(warmup_frames, last_read_frame_number)))
    print('-' * 88)
    print('{:<18} {:>14} {:>16} {:>8} {:>8} {:>14}'.format(
        'Interval Frame', 'Total Deteksi', 'Rata-rata/Frame', 'Maks', 'Min', 'Mulai Detik'
    ))
    print('-' * 88)

    for row in summary:
        label = '{}-{}'.format(row['start_frame'], row['end_frame'])
        print('{:<18} {:>14} {:>16.2f} {:>8} {:>8} {:>14.2f}'.format(
            label,
            row['total_deteksi'],
            row['rata_rata'],
            row['maks'],
            row['min'],
            row['mulai_detik'],
        ))

    print('-' * 88)
    grand_total = sum(row['total_deteksi'] for row in summary)
    total_frames = sum(row['end_frame'] - row['start_frame'] + 1 for row in summary)
    print('{:<18} {:>14} {:>16.2f}'.format(
        'TOTAL',
        grand_total,
        grand_total / max(total_frames, 1),
    ))

    labels = [f"{row['start_frame']}-{row['end_frame']}" for row in summary]
    totals = [row['total_deteksi'] for row in summary]
    avgs = [row['rata_rata'] for row in summary]

    fig, axes = plt.subplots(1, 2, figsize=(14, 4))

    axes[0].bar(range(len(labels)), totals)
    axes[0].set_title('Total Deteksi per Interval Frame')
    axes[0].set_xlabel('Interval Frame')
    axes[0].set_ylabel('Jumlah Deteksi')
    axes[0].set_xticks(range(len(labels)))
    axes[0].set_xticklabels(labels, rotation=45, ha='right', fontsize=8)

    axes[1].plot(range(len(labels)), avgs, marker='o')
    axes[1].set_title('Rata-rata Kendaraan per Frame')
    axes[1].set_xlabel('Interval Frame')
    axes[1].set_ylabel('Rata-rata')
    axes[1].set_xticks(range(len(labels)))
    axes[1].set_xticklabels(labels, rotation=45, ha='right', fontsize=8)

    plt.tight_layout()
    plt.savefig(save_path, dpi=120, bbox_inches='tight')
    plt.show()
    print('Grafik disimpan ke: {}'.format(save_path))

    return summary


review_summary = review_detections_per_interval(interval=REVIEW_INTERVAL)

"""## 8c. Analisis jumlah kendaraan per frame + tampilan gambar frame

Cell ini menghitung **berapa kendaraan yang terdeteksi pada setiap frame** setelah proses warmup, lalu menampilkan contoh gambar frame yang sudah diberi bounding box dan label jumlah kendaraan.

Output yang dibuat:
- CSV jumlah kendaraan per frame.
- Grafik tren jumlah kendaraan per frame.
- Folder gambar frame hasil deteksi, supaya hasil hitung bisa dicek manual.

Catatan: default gambar ditampilkan/disimpan setiap `REVIEW_INTERVAL` frame agar notebook tidak terlalu berat. Jika ingin semua frame, ubah `preview_every=1`, tetapi output bisa sangat banyak.

"""

def analyze_vehicle_count_per_frame(
    video_path=VIDEO_PATH,
    warmup_frames=WARMUP_FRAMES,
    save_csv_path='analisis_kendaraan_per_frame.csv',
    save_plot_path='grafik_kendaraan_per_frame.png',
    save_preview_dir='preview_kendaraan_per_frame',
    save_preview_sheet_path='preview_gambar_kendaraan_per_frame.png',
    show_every=REVIEW_INTERVAL,
    preview_every=REVIEW_INTERVAL,
    max_preview_images=12,
    save_preview_images=True,
    moving_average_window=30
):
    import csv
    from pathlib import Path

    if preview_every is not None and preview_every <= 0:
        raise ValueError('preview_every harus lebih besar dari 0, atau isi None jika tidak ingin preview.')

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f'Gagal membuka video: {video_path}')

    fps = cap.get(cv2.CAP_PROP_FPS) or 25

    ret, first_frame = cap.read()
    if not ret:
        cap.release()
        raise RuntimeError('Video tidak memiliki frame.')

    first_resized, first_gray = preprocess_frame(first_frame, width=RESIZE_WIDTH)
    avg_background = np.float32(first_gray)

    background_subtractor = cv2.createBackgroundSubtractorMOG2(
        history=300,
        varThreshold=32,
        detectShadows=True
    )

    frame_number = 1

    preview_dir = Path(save_preview_dir)
    if save_preview_images:
        preview_dir.mkdir(parents=True, exist_ok=True)

    while frame_number < warmup_frames:
        ret, frame = cap.read()
        if not ret:
            break

        warm_frame, warm_gray = preprocess_frame(frame, width=RESIZE_WIDTH)

        if METHOD == 'running_avg':
            cv2.accumulateWeighted(warm_gray, avg_background, RUNNING_AVG_ALPHA)
        elif METHOD == 'mog2':
            background_subtractor.apply(warm_frame)
        else:
            cap.release()
            raise ValueError(f'METHOD tidak dikenal: {METHOD}')

        frame_number += 1

    per_frame_results = []
    preview_images = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_number += 1

        current_frame, current_gray = preprocess_frame(frame, width=RESIZE_WIDTH)
        roi_mask = make_road_roi_mask(current_frame)

        if METHOD == 'running_avg':
            mask, avg_background = create_running_avg_mask(avg_background, current_gray)
        elif METHOD == 'mog2':
            mask = create_mog2_mask(background_subtractor, current_frame)
        else:
            cap.release()
            raise ValueError(f'METHOD tidak dikenal: {METHOD}')

        mask = apply_roi(mask, roi_mask)
        boxes = find_vehicle_candidates(mask)
        boxes = postprocess_boxes(boxes)

        jumlah_kendaraan = len(boxes)
        boxes_text = '; '.join(
            f'({x1},{y1},{x2},{y2})'
            for x1, y1, x2, y2, score in boxes
        )

        image_path = ''
        should_preview = preview_every is not None and frame_number % preview_every == 0

        if should_preview:
            annotated_frame = draw_detections(current_frame.copy(), boxes)

            cv2.putText(
                annotated_frame,
                f'Frame: {frame_number} | Kendaraan: {jumlah_kendaraan}',
                (20, 70),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.85,
                (0, 255, 255),
                2,
            )

            if save_preview_images:
                image_path = str(preview_dir / f'frame_{frame_number:06d}_kendaraan_{jumlah_kendaraan:02d}.png')
                cv2.imwrite(image_path, annotated_frame)

            if len(preview_images) < max_preview_images:
                preview_images.append((frame_number, jumlah_kendaraan, annotated_frame.copy()))

        per_frame_results.append({
            'frame': frame_number,
            'detik': frame_number / fps,
            'jumlah_kendaraan': jumlah_kendaraan,
            'boxes': boxes_text,
            'image_path': image_path,
        })

        if show_every and frame_number % show_every == 0:
            print(f'Frame {frame_number:>5} | Jumlah kendaraan: {jumlah_kendaraan}')

    cap.release()

    if not per_frame_results:
        print('Tidak ada frame yang diproses setelah warmup. Coba kecilkan WARMUP_FRAMES.')
        return []

    fieldnames = ['frame', 'detik', 'jumlah_kendaraan', 'boxes', 'image_path']
    with open(save_csv_path, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(per_frame_results)

    counts = [row['jumlah_kendaraan'] for row in per_frame_results]
    frames = [row['frame'] for row in per_frame_results]

    total_frame_dianalisis = len(per_frame_results)
    total_deteksi = sum(counts)
    rata_rata = total_deteksi / total_frame_dianalisis
    maksimum = max(counts)
    minimum = min(counts)
    frame_maksimum = [row['frame'] for row in per_frame_results if row['jumlah_kendaraan'] == maksimum]
    jumlah_gambar_disimpan = sum(1 for row in per_frame_results if row['image_path'])

    print('\nAnalisis jumlah kendaraan per frame')
    print(f'Metode                  : {METHOD}')
    print(f'Warmup                  : {warmup_frames} frame')
    print(f'Total frame dianalisis  : {total_frame_dianalisis}')
    print(f'Total deteksi           : {total_deteksi}')
    print(f'Rata-rata/frame         : {rata_rata:.2f}')
    print(f'Maks kendaraan/frame    : {maksimum}')
    print(f'Min kendaraan/frame     : {minimum}')
    print(f'Frame dengan nilai maks : {frame_maksimum[:20]}')
    if len(frame_maksimum) > 20:
        print(f'                         ... dan {len(frame_maksimum) - 20} frame lainnya')
    print(f'CSV disimpan ke         : {save_csv_path}')
    print(f'Grafik disimpan ke      : {save_plot_path}')
    print(f'Folder gambar frame     : {save_preview_dir}')
    print(f'Jumlah gambar disimpan  : {jumlah_gambar_disimpan}')
    print('=' * 60)

    try:
        import pandas as pd
        result_table = pd.DataFrame(per_frame_results)
        display(result_table.head(20))
    except ImportError:
        result_table = per_frame_results
        print('\n20 baris pertama:')
        for row in per_frame_results[:20]:
            print(row)

    if preview_images:
        cols = 2
        rows = int(np.ceil(len(preview_images) / cols))
        fig, axes = plt.subplots(rows, cols, figsize=(14, 5 * rows))
        axes = np.atleast_1d(axes).ravel()

        for ax, (frame_id, count, image) in zip(axes, preview_images):
            ax.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
            ax.set_title(f'Frame {frame_id} | Kendaraan terdeteksi: {count}')
            ax.axis('off')

        for ax in axes[len(preview_images):]:
            ax.axis('off')

        plt.tight_layout()
        plt.savefig(save_preview_sheet_path, dpi=120, bbox_inches='tight')
        plt.show()
        print(f'Preview gambar grid disimpan ke: {save_preview_sheet_path}')
    else:
        print('Tidak ada gambar preview yang ditampilkan. Cek nilai preview_every dan max_preview_images.')

    plt.figure(figsize=(14, 4))
    plt.plot(frames, counts, linewidth=1, label='Jumlah kendaraan per frame')

    if moving_average_window and len(counts) >= moving_average_window:
        kernel = np.ones(moving_average_window) / moving_average_window
        moving_avg = np.convolve(counts, kernel, mode='valid')
        moving_avg_frames = frames[moving_average_window - 1:]
        plt.plot(
            moving_avg_frames,
            moving_avg,
            linewidth=2,
            label=f'Rata-rata bergerak {moving_average_window} frame'
        )

    plt.title('Analisis Jumlah Kendaraan per Frame')
    plt.xlabel('Frame')
    plt.ylabel('Jumlah Kendaraan')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_plot_path, dpi=120, bbox_inches='tight')
    plt.show()

    return result_table

vehicle_count_per_frame = analyze_vehicle_count_per_frame(
    show_every=REVIEW_INTERVAL,
    preview_every=REVIEW_INTERVAL,
    max_preview_images=12,
    moving_average_window=REVIEW_INTERVAL
)

"""## 3.1 Implementasi ROI dan Ekstraksi Gerakan

Di sini kita akan:
1. Menggambar ROI (Region of Interest) — area jalan yang difokuskan
2. Menampilkan Foreground Mask — hasil deteksi gerakan setelah ROI diterapkan

ROI penting supaya kendaraan di luar jalan (misalnya pohon, gedung) tidak ikut terdeteksi.

"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

cap = cv2.VideoCapture(VIDEO_PATH)
ret, contoh_frame = cap.read()
cap.release()

if not ret:
    print("ERROR: Video tidak bisa dibaca. Cek VIDEO_PATH.")
else:
    tinggi_asli, lebar_asli = contoh_frame.shape[:2]
    skala = RESIZE_WIDTH / lebar_asli
    lebar_baru = RESIZE_WIDTH
    tinggi_baru = int(tinggi_asli * skala)
    frame_kecil = cv2.resize(contoh_frame, (lebar_baru, tinggi_baru))

    roi_mask = make_road_roi_mask(frame_kecil)

    kontur_roi, _ = cv2.findContours(roi_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    frame_dengan_roi = frame_kecil.copy()
    cv2.drawContours(frame_dengan_roi, kontur_roi, -1, (0, 255, 0), 3)

    frame_gelap_luar = frame_kecil.copy()
    area_luar_roi = roi_mask == 0
    frame_gelap_luar[area_luar_roi] = (frame_gelap_luar[area_luar_roi] * 0.25).astype(np.uint8)

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    axes[0].imshow(cv2.cvtColor(frame_dengan_roi, cv2.COLOR_BGR2RGB))
    axes[0].set_title('Gambar ROI — Garis Hijau = Batas Area Jalan', fontsize=12)
    axes[0].axis('off')

    axes[1].imshow(cv2.cvtColor(frame_gelap_luar, cv2.COLOR_BGR2RGB))
    axes[1].set_title('Visualisasi ROI — Area Gelap = Di Luar Proses', fontsize=12)
    axes[1].axis('off')

    plt.suptitle('3.1 Region of Interest (ROI)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

    print("Ukuran frame yang dipakai :", frame_kecil.shape)
    print("Luas ROI (piksel putih)   :", np.sum(roi_mask == 255))
    print("Luas total frame          :", frame_kecil.shape[0] * frame_kecil.shape[1])
    persen_roi = np.sum(roi_mask == 255) / (frame_kecil.shape[0] * frame_kecil.shape[1]) * 100
    print(f"Persentase area ROI       : {persen_roi:.1f}%")

cap2 = cv2.VideoCapture(VIDEO_PATH)

ret2, frame_pertama = cap2.read()
if ret2:
    _, gray_pertama = preprocess_frame(frame_pertama, width=RESIZE_WIDTH)
    bg_running = np.float32(gray_pertama)

    jumlah_warmup = 0
    while jumlah_warmup < WARMUP_FRAMES - 1:
        ret3, fr = cap2.read()
        if not ret3:
            break
        _, gray_warmup = preprocess_frame(fr, width=RESIZE_WIDTH)
        cv2.accumulateWeighted(gray_warmup, bg_running, RUNNING_AVG_ALPHA)
        jumlah_warmup += 1

    ret4, frame_setelah_warmup = cap2.read()
    cap2.release()

    if ret4:
        frame_resize, gray_setelah = preprocess_frame(frame_setelah_warmup, width=RESIZE_WIDTH)
        roi_mask2 = make_road_roi_mask(frame_resize)

        cv2.accumulateWeighted(gray_setelah, bg_running, RUNNING_AVG_ALPHA)
        bg_model = cv2.convertScaleAbs(bg_running)
        perbedaan = cv2.absdiff(gray_setelah, bg_model)
        _, mask_awal = cv2.threshold(perbedaan, RUNNING_AVG_THRESHOLD, 255, cv2.THRESH_BINARY)

        mask_bersih = clean_mask_conservative(mask_awal)
        mask_final = cv2.bitwise_and(mask_bersih, roi_mask2)

        fig2, axes2 = plt.subplots(1, 3, figsize=(18, 5))

        axes2[0].imshow(cv2.cvtColor(frame_resize, cv2.COLOR_BGR2RGB))
        axes2[0].set_title('Frame Asli (setelah warmup)', fontsize=11)
        axes2[0].axis('off')

        axes2[1].imshow(mask_awal, cmap='gray')
        axes2[1].set_title('Foreground Mask — Sebelum ROI', fontsize=11)
        axes2[1].axis('off')

        axes2[2].imshow(mask_final, cmap='gray')
        axes2[2].set_title('Foreground Mask — Setelah ROI Diterapkan', fontsize=11)
        axes2[2].axis('off')

        plt.suptitle('3.1 Ekstraksi Gerakan (Running Average)', fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.show()

        print("Piksel putih mask (gerakan terdeteksi) sebelum ROI :", np.sum(mask_awal == 255))
        print("Piksel putih mask (gerakan terdeteksi) setelah ROI :", np.sum(mask_final == 255))
    else:
        print("Tidak cukup frame untuk preview foreground mask.")
        cap2.release()
else:
    print("ERROR: Tidak bisa membaca frame untuk foreground mask.")
    cap2.release()

"""## 3.2 Analisis Operasi Morfologi terhadap Noise

Operasi morfologi digunakan untuk membersihkan noise pada foreground mask:
- **OPEN** (erosi lalu dilasi): menghapus titik-titik kecil (noise)
- **CLOSE** (dilasi lalu erosi): menutup celah kecil di dalam blob kendaraan
- **DILATE**: memperlebar blob sedikit agar kontur kendaraan lebih lengkap

Di sini kita bandingkan mask sebelum dan sesudah morfologi.

"""

cap3 = cv2.VideoCapture(VIDEO_PATH)

ret_a, frame_a = cap3.read()

if ret_a:

    _, gray_a = preprocess_frame(frame_a, width=RESIZE_WIDTH)
    bg_morfo = np.float32(gray_a)

    for _ in range(WARMUP_FRAMES - 1):

        ret_b, fr_b = cap3.read()

        if not ret_b:
            break

        _, gray_b = preprocess_frame(fr_b, width=RESIZE_WIDTH)

        cv2.accumulateWeighted(
            gray_b,
            bg_morfo,
            RUNNING_AVG_ALPHA
        )

    ret_c, frame_c = cap3.read()

    cap3.release()

    if ret_c:

        frame_c_resize, gray_c = preprocess_frame(
            frame_c,
            width=RESIZE_WIDTH
        )

        cv2.accumulateWeighted(
            gray_c,
            bg_morfo,
            RUNNING_AVG_ALPHA
        )

        bg_model_c = cv2.convertScaleAbs(bg_morfo)

        perbedaan_c = cv2.absdiff(gray_c, bg_model_c)

        _, mask_sebelum = cv2.threshold(
            perbedaan_c,
            RUNNING_AVG_THRESHOLD,
            255,
            cv2.THRESH_BINARY
        )

        kernel_open = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE,
            (3, 3)
        )

        kernel_close = cv2.getStructuringElement(
            cv2.MORPH_RECT,
            (7, 7)
        )

        kernel_dilate = cv2.getStructuringElement(
            cv2.MORPH_RECT,
            (5, 3)
        )

        mask_setelah_open = cv2.morphologyEx(
            mask_sebelum,
            cv2.MORPH_OPEN,
            kernel_open,
            iterations=2
        )

        mask_setelah_close = cv2.morphologyEx(
            mask_setelah_open,
            cv2.MORPH_CLOSE,
            kernel_close,
            iterations=1
        )

        mask_setelah_dilate = mask_setelah_close.copy()

        if DILATE_ITER > 0:

            mask_setelah_dilate = cv2.dilate(
                mask_setelah_close,
                kernel_dilate,
                iterations=DILATE_ITER
            )

        kontur_sebelum, _ = cv2.findContours(
            mask_sebelum,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )

        kontur_open, _ = cv2.findContours(
            mask_setelah_open,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )

        kontur_close, _ = cv2.findContours(
            mask_setelah_close,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )

        kontur_dilate, _ = cv2.findContours(
            mask_setelah_dilate,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )


        fig3, axes3 = plt.subplots(2, 2, figsize=(16, 10))

        axes3[0][0].imshow(mask_sebelum, cmap='gray')

        axes3[0][0].set_title(
            f'Sebelum Morfologi\n({len(kontur_sebelum)} kontur)',
            fontsize=11
        )

        axes3[0][0].axis('off')

        axes3[0][1].imshow(mask_setelah_open, cmap='gray')

        axes3[0][1].set_title(
            f'Setelah OPEN (hapus noise kecil)\n({len(kontur_open)} kontur)',
            fontsize=11
        )

        axes3[0][1].axis('off')

        axes3[1][0].imshow(mask_setelah_close, cmap='gray')

        axes3[1][0].set_title(
            f'Setelah CLOSE (tutup celah)\n({len(kontur_close)} kontur)',
            fontsize=11
        )

        axes3[1][0].axis('off')

        axes3[1][1].imshow(mask_setelah_dilate, cmap='gray')

        axes3[1][1].set_title(
            f'Setelah DILATE (perlebar blob)\n({len(kontur_dilate)} kontur)',
            fontsize=11
        )

        axes3[1][1].axis('off')

        plt.suptitle(
            '3.2 Perbandingan Sebelum dan Sesudah Operasi Morfologi',
            fontsize=14,
            fontweight='bold'
        )

        plt.tight_layout()
        plt.show()


        print("Ringkasan jumlah kontur di tiap tahap morfologi:")
        print(f"  Sebelum morfologi : {len(kontur_sebelum)} kontur")

        print(
            f"  Setelah OPEN      : {len(kontur_open)} kontur "
            f"(noise kecil berkurang)"
        )

        print(f"  Setelah CLOSE     : {len(kontur_close)} kontur")

        print(f"  Setelah DILATE    : {len(kontur_dilate)} kontur")

        pengurangan = len(kontur_sebelum) - len(kontur_dilate)

        if len(kontur_sebelum) > 0:
            persen_berkurang = (
                pengurangan / len(kontur_sebelum)
            ) * 100
        else:
            persen_berkurang = 0

        print(
            f"\nTotal pengurangan kontur (noise): "
            f"{pengurangan} ({persen_berkurang:.1f}%)"
        )

        print(
            "Operasi morfologi berhasil "
            "mengurangi noise sebelum deteksi kendaraan."
        )

    else:
        print("Frame tidak cukup untuk analisis morfologi.")

else:
    print("Video tidak bisa dibuka.")

cap3.release()

"""## 3.3 Evaluasi Filtrasi Perspektif dan NMS

Setelah morfologi, kita filter kontur berdasarkan:
1. **Filter perspektif** — kendaraan jauh (atas frame) boleh lebih kecil, kendaraan dekat (bawah frame) harus lebih besar
2. **Filter aspek rasio** — marka jalan sangat panjang-tipis, kendaraan lebih kotak
3. **NMS (Non-Maximum Suppression)** — buang bounding box yang terlalu tumpang tindih

Di sini kita tampilkan bounding box sebelum NMS vs sesudah NMS, dan analisis kendaraan dekat vs jauh.

"""

cap4 = cv2.VideoCapture(VIDEO_PATH)
ret_d, frame_d = cap4.read()
if ret_d:
    _, gray_d = preprocess_frame(frame_d, width=RESIZE_WIDTH)
    bg_nms = np.float32(gray_d)

    for _ in range(WARMUP_FRAMES - 1):
        ret_e, fr_e = cap4.read()
        if not ret_e:
            break
        _, gray_e = preprocess_frame(fr_e, width=RESIZE_WIDTH)
        cv2.accumulateWeighted(gray_e, bg_nms, RUNNING_AVG_ALPHA)

    ret_f, frame_f = cap4.read()
    cap4.release()

    if ret_f:
        frame_f_resize, gray_f = preprocess_frame(frame_f, width=RESIZE_WIDTH)
        roi_mask3 = make_road_roi_mask(frame_f_resize)

        # Hitung mask
        cv2.accumulateWeighted(gray_f, bg_nms, RUNNING_AVG_ALPHA)
        bg_model_f = cv2.convertScaleAbs(bg_nms)
        perbedaan_f = cv2.absdiff(gray_f, bg_model_f)
        _, mask_raw = cv2.threshold(perbedaan_f, RUNNING_AVG_THRESHOLD, 255, cv2.THRESH_BINARY)
        mask_bersih3 = clean_mask_conservative(mask_raw)
        mask_roi3 = cv2.bitwise_and(mask_bersih3, roi_mask3)

        # Ambil semua kontur tanpa filter
        tinggi_frame, lebar_frame = mask_roi3.shape[:2]
        semua_kontur, _ = cv2.findContours(mask_roi3, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        semua_boxes_kasar = []
        for kontur in semua_kontur:
            x, y, w, h = cv2.boundingRect(kontur)
            area = cv2.contourArea(kontur)
            semua_boxes_kasar.append([x, y, x + w, y + h, float(area)])

        boxes_terfilter = find_vehicle_candidates(mask_roi3)

        boxes_nms = postprocess_boxes(boxes_terfilter)


        frame_tanpa_filter = frame_f_resize.copy()
        for bx in semua_boxes_kasar:
            cv2.rectangle(frame_tanpa_filter, (bx[0], bx[1]), (bx[2], bx[3]), (0, 0, 255), 1)

        frame_sebelum_nms = frame_f_resize.copy()
        for bx in boxes_terfilter:
            cv2.rectangle(frame_sebelum_nms, (bx[0], bx[1]), (bx[2], bx[3]), (0, 165, 255), 2)

        frame_sesudah_nms = frame_f_resize.copy()
        for i, bx in enumerate(boxes_nms):
            cv2.rectangle(frame_sesudah_nms, (bx[0], bx[1]), (bx[2], bx[3]), (0, 255, 0), 2)
            cv2.putText(frame_sesudah_nms, f'K{i+1}', (bx[0], bx[1] - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        fig4, axes4 = plt.subplots(1, 3, figsize=(20, 6))

        axes4[0].imshow(cv2.cvtColor(frame_tanpa_filter, cv2.COLOR_BGR2RGB))
        axes4[0].set_title(f'Semua Kontur Tanpa Filter\n({len(semua_boxes_kasar)} kotak merah)', fontsize=10)
        axes4[0].axis('off')

        axes4[1].imshow(cv2.cvtColor(frame_sebelum_nms, cv2.COLOR_BGR2RGB))
        axes4[1].set_title(f'Setelah Filter Perspektif (Sebelum NMS)\n({len(boxes_terfilter)} kotak oranye)', fontsize=10)
        axes4[1].axis('off')

        axes4[2].imshow(cv2.cvtColor(frame_sesudah_nms, cv2.COLOR_BGR2RGB))
        axes4[2].set_title(f'Bounding Box Akhir (Setelah NMS)\n({len(boxes_nms)} kotak hijau)', fontsize=10)
        axes4[2].axis('off')

        plt.suptitle('3.3 Filtrasi Perspektif dan NMS', fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.show()

        print("\nAnalisis kendaraan dekat vs jauh (berdasarkan posisi Y):")
        print("=" * 55)

        kendaraan_jauh   = []
        kendaraan_tengah = []
        kendaraan_dekat  = []

        for bx in boxes_nms:
            x1, y1, x2, y2, luas = bx
            tengah_y = (y1 + y2) / 2
            rasio_y = tengah_y / tinggi_frame

            lebar_box = x2 - x1
            tinggi_box = y2 - y1

            if rasio_y < 0.42:
                kendaraan_jauh.append({
                    'rasio_y': rasio_y, 'lebar': lebar_box,
                    'tinggi': tinggi_box, 'luas': luas
                })
            elif rasio_y < 0.68:
                kendaraan_tengah.append({
                    'rasio_y': rasio_y, 'lebar': lebar_box,
                    'tinggi': tinggi_box, 'luas': luas
                })
            else:
                kendaraan_dekat.append({
                    'rasio_y': rasio_y, 'lebar': lebar_box,
                    'tinggi': tinggi_box, 'luas': luas
                })

        print(f"Zona JAUH  (atas frame)  : {len(kendaraan_jauh)} kendaraan")
        if kendaraan_jauh:
            rata_luas_jauh = sum(k['luas'] for k in kendaraan_jauh) / len(kendaraan_jauh)
            print(f"  Rata-rata luas box     : {rata_luas_jauh:.0f} piksel²")
            print(f"  Min area diizinkan     : {MIN_AREA_TOP} piksel²")

        print(f"\nZona TENGAH (tengah frame): {len(kendaraan_tengah)} kendaraan")
        if kendaraan_tengah:
            rata_luas_tengah = sum(k['luas'] for k in kendaraan_tengah) / len(kendaraan_tengah)
            print(f"  Rata-rata luas box     : {rata_luas_tengah:.0f} piksel²")
            print(f"  Min area diizinkan     : {MIN_AREA_MIDDLE} piksel²")

        print(f"\nZona DEKAT (bawah frame) : {len(kendaraan_dekat)} kendaraan")
        if kendaraan_dekat:
            rata_luas_dekat = sum(k['luas'] for k in kendaraan_dekat) / len(kendaraan_dekat)
            print(f"  Rata-rata luas box     : {rata_luas_dekat:.0f} piksel²")
            print(f"  Min area diizinkan     : {MIN_AREA_BOTTOM} piksel²")

        print("=" * 55)
        print(f"Total kendaraan terdeteksi pada frame ini: {len(boxes_nms)}")
        print("\nKesimpulan: Kendaraan dekat memiliki bounding box lebih besar")
        print("karena secara perspektif, objek dekat tampak lebih besar di kamera.")
    else:
        print("Frame tidak cukup.")
        cap4.release()
else:
    print("Video tidak bisa dibuka.")
    cap4.release()

"""## 3.4 Analisis Review Per-Interval dan Batasan Sistem

Di sini kita akan:
1. Menampilkan **tabel jumlah kendaraan per interval** dari hasil CSV yang sudah disimpan
2. Membahas **keterbatasan metode Running Average** berdasarkan data yang diperoleh

"""

import pandas as pd
import matplotlib.pyplot as plt
import os

path_csv = 'hasil_per_frame.csv'

if not os.path.exists(path_csv):
    print(f"File '{path_csv}' belum ada.")
    print("Jalankan dulu Cell 8c (analyze_vehicle_count_per_frame) untuk membuat CSV.")
else:
    df = pd.read_csv(path_csv)
    print(f"CSV berhasil dibaca. Total baris: {len(df)}")
    print(f"Kolom yang tersedia: {list(df.columns)}")
    print()

    df['interval'] = (df['frame'] // REVIEW_INTERVAL) + 1

    ringkasan_interval = df.groupby('interval').agg(
        frame_mulai   = ('frame', 'min'),
        frame_akhir   = ('frame', 'max'),
        detik_mulai   = ('detik', 'min'),
        detik_akhir   = ('detik', 'max'),
        rata_kendaraan = ('jumlah_kendaraan', 'mean'),
        maks_kendaraan = ('jumlah_kendaraan', 'max'),
        min_kendaraan  = ('jumlah_kendaraan', 'min'),
        total_deteksi  = ('jumlah_kendaraan', 'sum'),
    ).reset_index()

    ringkasan_interval['rata_kendaraan'] = ringkasan_interval['rata_kendaraan'].round(2)
    ringkasan_interval['detik_mulai']    = ringkasan_interval['detik_mulai'].round(1)
    ringkasan_interval['detik_akhir']    = ringkasan_interval['detik_akhir'].round(1)

    # Tampilkan tabel
    print("=" * 70)
    print(f"TABEL JUMLAH KENDARAAN PER INTERVAL ({REVIEW_INTERVAL} frame/interval)")
    print("=" * 70)
    print(ringkasan_interval.to_string(index=False))
    print("=" * 70)

    plt.figure(figsize=(14, 5))

    plt.bar(ringkasan_interval['interval'],
            ringkasan_interval['rata_kendaraan'],
            color='steelblue', alpha=0.7, label='Rata-rata kendaraan')

    plt.plot(ringkasan_interval['interval'],
             ringkasan_interval['maks_kendaraan'],
             color='red', marker='o', linewidth=1.5, label='Maks kendaraan')

    plt.xlabel('Nomor Interval')
    plt.ylabel('Jumlah Kendaraan')
    plt.title(f'Analisis Kendaraan Per Interval ({REVIEW_INTERVAL} frame/interval)')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    total_interval = len(ringkasan_interval)
    rata_global    = df['jumlah_kendaraan'].mean()
    maks_global    = df['jumlah_kendaraan'].max()
    frame_maks     = df.loc[df['jumlah_kendaraan'].idxmax(), 'frame']

    print()
    print("Ringkasan Global:")
    print(f"  Total interval         : {total_interval}")
    print(f"  Rata-rata kendaraan    : {rata_global:.2f} per frame")
    print(f"  Maksimum kendaraan     : {maks_global} (pada frame {frame_maks})")
    print(f"  Interval paling ramai  : interval {ringkasan_interval['rata_kendaraan'].idxmax() + 1}")

    print()
    print("=" * 70)
    print("PEMBAHASAN KETERBATASAN METODE RUNNING AVERAGE")
    print("=" * 70)

    std_antar_interval = ringkasan_interval['rata_kendaraan'].std()
    rentang_deteksi = maks_global - df['jumlah_kendaraan'].min()

    print()
    print("1. MASALAH OBJEK YANG BERHENTI (Stopped Vehicle Problem)")
    print("   Ketika kendaraan berhenti (misalnya di lampu merah), lama-kelamaan")
    print("   kendaraan tersebut 'diserap' ke background model karena Running Average")
    print(f"   terus memperbarui background dengan alpha = {RUNNING_AVG_ALPHA}.")
    print("   Akibatnya kendaraan yang diam tidak terdeteksi meski masih ada di jalan.")
    print()
    print("2. KEPEKAAN TERHADAP PERUBAHAN CAHAYA")
    print("   Perubahan cahaya mendadak (misalnya awan menutupi matahari)")
    print("   menyebabkan hampir seluruh frame terdeteksi sebagai gerakan.")
    print("   Ini terlihat dari lonjakan jumlah kendaraan yang tidak wajar.")
    print(f"   Rentang deteksi dalam video ini: 0 – {rentang_deteksi} kendaraan per frame")
    print()
    print("3. KETERGANTUNGAN PADA ALPHA (LEARNING RATE)")
    print(f"   Alpha saat ini: {RUNNING_AVG_ALPHA}")
    print("   Alpha kecil  → background lambat belajar → objek statis terus terdeteksi")
    print("   Alpha besar  → background cepat belajar → kendaraan lambat 'menghilang'")
    print("   Tidak ada nilai alpha yang sempurna untuk semua kondisi video.")
    print()
    print("4. TIDAK ADA TRACKING ANTAR FRAME")
    print("   Sistem ini mendeteksi gerakan tiap frame secara terpisah.")
    print("   Satu kendaraan yang bergerak bisa terdeteksi sebagai")
    print("   jumlah berbeda di setiap frame (kadang 1, kadang 2 box).")
    print("   Variasi antar interval:", f"{std_antar_interval:.2f} kendaraan (std dev)")
    print()
    print("5. MARKA JALAN DAN BAYANGAN")
    print("   Marka jalan yang terekspos oleh gerakan kendaraan bisa")
    print("   sesekali lolos dari filter dan dihitung sebagai kendaraan.")
    print("   Filter perspektif dan rectangularity sudah mengurangi ini,")
    print("   tapi tidak bisa menghilangkan 100%.")
    print()
    print("Kesimpulan:")
    print("Running Average cocok untuk video CCTV statis dengan pencahayaan stabil.")
    print("Untuk kondisi lebih kompleks, dibutuhkan metode seperti MOG2, GMM,")
    print("atau metode berbasis deep learning seperti YOLO.")
    print("=" * 70)

"""## 9. Tampilkan video hasil"""

display(Video(OUTPUT_PATH, embed=True, width=800))